import { Inter } from 'next/font/google'
import Head from 'next/head';
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const currentPath = params?.slug || ""; // Next.jsの動的ルーティングで現在のパスを取得

  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🧭</text></svg>"
        />
        <title>IT Trip Navigator</title>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <nav>
          {/* パスが "/" ではない場合のみリンクを表示 */}
          {currentPath !== "" && (
            <Link href="/">日程調整に戻る</Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}