import localFont from "next/font/local";
import "./globals.css";
import { Noto_Sans_JP } from 'next/font/google'
import Link from 'next/link';

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
          <nav>
            <Link href="/">日程調整に戻る</Link>
          </nav>
        {children}
      </body>
    </html>
  );
}
